### ISSUE TITLE
keykobo.com is a false positive

### ISSUE THREAD

**Issue by nopjmp** [jarelllama/Scam-Blocklist#347]
I'm not seeing any justification for keykobo.com being on the list and it appears to be a legit website and [r/MechanicalKeyboards](https://www.reddit.com/r/MechanicalKeyboards/) seems to not think they are a scam.

**Comment by jarelllama** [comment]
Confirmed false positive. Thanks for reporting! All lists have been rebuilt as of 1:35 AM UTC.

Trail:
https://en.zfrontier.com/products/keykobo-taiji lists https://www.instagram.com/keykobo/ as official Instagram account which lists www.keykobo.com as official website.

Was picked up by the Google Search source for using a common scam About Us page.

https://www.google.com/search?q=%22we+love+every+passion+and+interest+on+Earth+because+it+is+a+reference+to+your+UNIQUENESS.+And+to+create+a+perfect+consumption+experience+for+you+is+our+core+vision%3A%22&sca_upv=1
